@startuml

skinparam defaultTextAlignment center

skinparam component {
  fontStyle bold
  fontColor white
  backgroundColor #586ba4
  borderColor #222
  borderThickness 2
}

skinparam component<< New idea >> {
  fontColor black
  backgroundColor #ffe696
}

skinparam component<< Language >> {
  fontColor white
  backgroundColor #d95448
}

component scala as "Scala" << Language >>

@enduml
