@startuml

skinparam defaultTextAlignment center

skinparam component {
  fontStyle bold
  borderColor #222
  borderThickness 2
}

skinparam component<< Library >> {
  fontColor white
  backgroundColor #586ba4
}

skinparam component<< New idea >> {
  fontColor black
  backgroundColor #ffe696
}

skinparam component<< Language >> {
  fontColor white
  backgroundColor #d95448
}

component scala as "Scala" << Language >>

component cats as "cats" << Library >>
component scalatest as "ScalaTest" << Library >>

cats --> scala
scalatest --> scala

component cats_effect as "cats-effect" << Library >>
cats_effect --> cats

component functor as "Functor" << New idea >>
component monad as "Monad" << New idea >>

functor ---> cats
monad ---> cats

component side_effect as "Side effect" << New idea >>
side_effect --> cats_effect

@enduml
