@startuml

skinparam defaultTextAlignment center

skinparam component {
  fontStyle bold
  fontColor white
  backgroundColor #586ba4
  borderColor #222
  borderThickness 2
}

skinparam component<< New idea >> {
  fontColor black
  backgroundColor #ffe696
}

skinparam component<< Language >> {
  fontColor white
  backgroundColor #d95448
}

component scala as "Scala" << Language >>

component cats as "cats" << Library >>
component scalatest as "ScalaTest" << Library >>

cats --> scala
scalatest --> scala

component cats_effect as "cats-effect" << Library >>
cats_effect --> cats

component functor as "Functor" << New idea >>
component monad as "Monad" << New idea >>

component side_effect as "Side effect" << New idea >>
side_effect --> cats_effect

interface category_theory as "Category theory"

functor --> category_theory
monad --> category_theory

component haskell as "Haskell" << Language >>
component kotlin as "Kotlin" << Language >>

category_theory --> cats
category_theory ---> haskell
category_theory ---> kotlin

interface kinda_functional as "Somewhat functional"
component javascript as "JavaScript" << Language >>
component python as "Python" << Language >>
component java as "Java" << Language >>
kinda_functional ----> javascript
kinda_functional ----> python
kinda_functional ----> java

interface not_functional as "Not functional"
component cpp as "C++" << Language >>
not_functional ----> cpp

@enduml
