@startuml

skinparam defaultTextAlignment center

skinparam component {
  fontStyle bold
  fontColor white
  backgroundColor #586ba4
  borderColor #222
  borderThickness 2
}

component semigroup as "Semigroup"
note left of semigroup: Can plus

component monoid as "Monoid"
note left of monoid: Has zero

semigroup --> monoid

component functor as "Functor"
note right of functor: Inner structure can be changed with map

component applicative as "Applicative"
note right of applicative: Can wrap; and outer structures can interact

component monad as "Monad"
note right of monad: Inner structure can influence outer structures with flatMap

functor --> applicative
applicative --> monad
@enduml
