@startuml

skinparam defaultTextAlignment center

skinparam component {
  fontStyle bold
  fontColor white
  backgroundColor #586ba4
  borderColor #222
  borderThickness 2
}

skinparam component<< New idea >> {
  fontColor black
  backgroundColor #ffe696
}

skinparam component<< Language >> {
  fontColor white
  backgroundColor #d95448
}

component scala as "Scala" << Language >>

component cats as "cats" << Library >>
component scalatest as "ScalaTest" << Library >>

cats --> scala
scalatest --> scala

component cats_effect as "cats-effect" << Library >>
cats_effect --> cats

component functor as "Functor" << New idea >>
component monad as "Monad" << New idea >>

interface category_theory as "Category theory"

functor --> category_theory
monad --> category_theory

component haskell as "Haskell" << Language >>
component kotlin as "Kotlin" << Language >>

category_theory --> cats
category_theory ---> haskell
category_theory ---> kotlin

component circe as "circe" << Library >>
component http4s as "http4s" << Library >>

circe --> cats_effect
http4s --> cats_effect

note left of circe : JSON parsing
note right of http4s : web server

component play as "Play" << Library >>
component akka as "Akka" << Library >>

play --> scala
akka --> scala

component java as "Java" << Language >>
component spring as "Spring" << Library >>

scala --> java
spring --> java

@enduml
